default: &default
  adapter: postgis
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: API_DEVELOPMENT
  username: API_USER
  password: API_PASSWORD
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

test:
  <<: *default
  database: opj_test
  username: API_USER
  password: API_PASSWORD
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
