default: &default
  adapter: postgis
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: API_DEVELOPMENT
  username: API_USER
  password: API_PASSWORD
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

test:
  <<: *default
  database: opj_test
  username: API_USER
  password: API_PASSWORD
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: opj_production
    username: opj
    password: <%= ENV["OPJ_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: opj_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: opj_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: opj_production_cable
    migrations_paths: db/cable_migrate
